name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # replace with your default branch if not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert Markdown to HTML
        uses: manubot/process@v1
        with:
          from_format: markdown
          to_format: html
          input_path: README.md
          output_path: index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
