name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # replace with your default branch if not "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert Markdown to HTML
        uses: docker://pandoc/core:2.14.0.3 
        with:
          args: >-
            -- from markdown
            -- to html
            -- output index.html
           README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
